require "#{File.dirname(__FILE__)}/scraper/string_extensions"
require "#{File.dirname(__FILE__)}/scraper/base"
require "#{File.dirname(__FILE__)}/scraper/imdb"
require "#{File.dirname(__FILE__)}/scraper/metacritic"
require "#{File.dirname(__FILE__)}/scraper/rotten_tomatoes"
require "#{File.dirname(__FILE__)}/scraper/freebase"