require 'myimdb/scraper/string_extensions'
require 'myimdb/scraper/base'
require 'myimdb/scraper/imdb'
require 'myimdb/scraper/metacritic'
require 'myimdb/scraper/rotten_tomatoes'
require 'myimdb/scraper/freebase'